#ifndef DATASETTESTWIDGET_H
#define DATASETTESTWIDGET_H

#include <QWidget>
#include "Project/DatasetTestModel.h"
#include "Project/Project.h"

using namespace ProjectData;
namespace Ui{class DatasetTestWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

/**
 * The DatasetTestWidget class.
 */
class DatasetTestWidget : public QWidget{
	Q_OBJECT
		
	public:
        DatasetTestWidget(QWidget *parent = 0);
		~DatasetTestWidget();
		void setModel(DatasetTestModel* model);
		bool hasModel();

	private slots:
        void modelChanged(ChangeType type);
		void closeBtnPressed();
		void startTest();
        void datasetSelected(QString name);
        void networkSelected(QString name);

	private:
        void genNetworkList();

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::DatasetTestWidget *ui;
        /** Current model pointer. */
		DatasetTestModel* model;
        /** Used as empty model for tableView. */
		DatasetEditModel* emptyModel;
};

}

#endif // DATASETTESTWIDGET_H
