/*
 * This file is part of Neural network Creator, backpropagation
 * simulator and multilayer neural network IDE.
 * Copyright (C) 2013  Petr Kačer <kacerpetr@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef DATASETTESTWIDGET_H
#define DATASETTESTWIDGET_H

#include <QWidget>
#include "Project/DatasetTestModel.h"
#include "Project/Project.h"

using namespace ProjectData;
namespace Ui{class DatasetTestWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

/**
 * The DatasetTestWidget class.
 */
class DatasetTestWidget : public QWidget{
	Q_OBJECT
		
	public:
        DatasetTestWidget(QWidget *parent = 0);
		~DatasetTestWidget();
		void setModel(DatasetTestModel* model);
		bool hasModel();

	private slots:
        void modelChanged(ChangeType type);
		void closeBtnPressed();
		void startTest();
        void datasetSelected(QString name);
        void networkSelected(QString name);

	private:
        void genNetworkList();

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::DatasetTestWidget *ui;
        /** Current model pointer. */
		DatasetTestModel* model;
        /** Used as empty model for tableView. */
		DatasetEditModel* emptyModel;
};

}

#endif // DATASETTESTWIDGET_H
