#ifndef LEARNINGWIDGET_H
#define LEARNINGWIDGET_H

#include <QWidget>
#include "Project/LearningConfigModel.h"
#include "GuiPart/NetParamWidget.h"
#include "GuiPart/Plot1D.h"
#include "Application/MainWindow.h"

using namespace ProjectData;
namespace Ui{class LearningWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

//main window forward declaration
class MainWindow;

/**
 * The LearningWidget class.
 */
class LearningWidget : public QWidget{
	Q_OBJECT
		
	public:
        LearningWidget(MainWindow* mainWin = NULL);
		~LearningWidget();
		void setModel(LearningConfigModel* model);
		bool hasModel();

	private slots:
		void modelChanged(ChangeType type);
		void closeBtnPressed();
		void startLearning();
		void stopLearning();
        void learningStoped();
		void updateLearning(int iteration, long time, double error);
		void datasetSelected(QString name);
		void networkSelected(QString name);
		void lrnCoefChanged(double value);
		void maxIterChanged(int value);
		void maxErrChanged(double value);
		void maxTimeChanged(int value);
        void resetLearning();

	private:
        void genNetworkList();
        void setPlot(Plot1D* plot);

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::LearningWidget *ui;
        /** Current model pointer. */
		LearningConfigModel* model;
        /** Net param widget pointer. */
		NetParamWidget* npw;
        /** MainWindow pointer, because of connecting model opened by network selection. */
        MainWindow* mainWin;
};

}

#endif // LEARNINGWIDGET_H
