#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QWidget>
#include <QLabel>
#include <QListWidgetItem>
#include "WelcomeWidget.h"
#include "DatasetEditWidget.h"
#include "TopologyWidget.h"
#include "LearningWidget.h"
#include "DatasetTestWidget.h"
#include "HelpWidget.h"
#include "NoModelWidget.h"
#include "OutputGraphWidget.h"
#include "Project/Workspace.h"
#include "Dialog/FileNameDialog.h"

using namespace ProjectData;
namespace Ui{class MainWindow;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

//forward declaration of learning widget because of
//storing this pointer in LearningConfigWidget
class LearningWidget;

/**
 * The MainWindow class.
 */
class MainWindow : public QMainWindow{
	Q_OBJECT
		
	public:
        MainWindow(QWidget *parent = 0);
		~MainWindow();
		void setWidget(QWidget* widget);
		void setModel(BaseModel* model);
		void checkMainButtons(int button);
		void updateOpenedList();
		void connectModel(BaseModel* mdl);
		virtual void closeEvent(QCloseEvent *event);

	public slots:
		void showAboutDialog();
		void showAboutQt();
        void showSettingsDialog();
		void editMenuItemPressed(int button);
		void showContextMenu();
		void projectViewTreeClick(QModelIndex index);
		void showHelp();
		void newProject();
        void newDataset();
		void newNeuralNetwork();
		void newLearningConfig();
		void newDatasetTest();
		void newGraphTest();
		void mdlSaved(BaseModel* mdl);
		void mdlOpened(BaseModel* mdl);
		bool closeEdit(BaseModel* mdl, bool closeApp = false);
		void save();
		void saveAll();
		void openProject();
		void closeProject();
		void renameModel();
		void removeModel();
        void duplicateDataset();
		void openRecent(QString path);
		void showOpened(QListWidgetItem* item);

	private:
        /** Autogenerated stuff, user interface class pointer. */
        Ui::MainWindow *ui;
        /** Showed when no files of selected category are opened. */
		NoModelWidget* noModel;
        /** Welcome screen widget. */
        WelcomeWidget* welcome;
        /** Dataset editor widget. */
        DatasetEditWidget* dataset;
        /** Network topology eitor. */
        TopologyWidget* topology;
        /** Learning screen. */
        LearningWidget* learning;
        /** Dataset test widget. */
        DatasetTestWidget* datasetTest;
        /** Output graph widget. */
        OutputGraphWidget* graphTest;
        /** Help view widget. */
        HelpWidget* help;
        /** Containss all projects. */
		Workspace* workspace;
        /** Pointer to currently selected edit widget. */
        QWidget* currentWidget;
        /** Pointer to currently selected model. */
        BaseModel* currentModel;
};

}

#endif // MAINWINDOW_H
