/*
 * This file is part of Neural network Creator, backpropagation
 * simulator and multilayer neural network IDE.
 * Copyright (C) 2013  Petr Kačer <kacerpetr@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef OUTPUTGRAPHWIDGET_H
#define OUTPUTGRAPHWIDGET_H

#include <QWidget>
#include "Project/GraphTestModel.h"

using namespace ProjectData;
namespace Ui{class OutputGraphWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

/**
 * The OutputGraphWidget class.
 */
class OutputGraphWidget : public QWidget{
	Q_OBJECT
		
	public:
        OutputGraphWidget(QWidget *parent = 0);
		~OutputGraphWidget();
		void setModel(GraphTestModel* model);
		bool hasModel();

	private slots:
        void modelChanged(ChangeType type);
		void drawGraph();
		void outputChanged(int value);
		void closeBtnPressed();
        void networkSelected(QString name);
        void datasetSelected(QString name);

	private:
        void setPlot();
        void hideDatasetSelection(bool hide);
        void genNetworkList();

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::OutputGraphWidget *ui;
        /** Current model pointer. */
		GraphTestModel* model;
};

}

#endif // OUTPUTGRAPHWIDGET_H
