#ifndef OUTPUTGRAPHWIDGET_H
#define OUTPUTGRAPHWIDGET_H

#include <QWidget>
#include "Project/GraphTestModel.h"

using namespace ProjectData;
namespace Ui{class OutputGraphWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

/**
 * The OutputGraphWidget class.
 */
class OutputGraphWidget : public QWidget{
	Q_OBJECT
		
	public:
        OutputGraphWidget(QWidget *parent = 0);
		~OutputGraphWidget();
		void setModel(GraphTestModel* model);
		bool hasModel();

	private slots:
        void modelChanged(ChangeType type);
		void drawGraph();
		void outputChanged(int value);
		void closeBtnPressed();
        void networkSelected(QString name);

	private:
        void setPlot();
        void genNetworkList();

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::OutputGraphWidget *ui;
        /** Current model pointer. */
		GraphTestModel* model;
};

}

#endif // OUTPUTGRAPHWIDGET_H
