/*
 * This file is part of Neural network Creator, backpropagation
 * simulator and multilayer neural network IDE.
 * Copyright (C) 2013  Petr Kačer <kacerpetr@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef TOPOLOGYWIDGET_H
#define TOPOLOGYWIDGET_H

#include <QWidget>
#include <QList>
#include <QVBoxLayout>
#include "GuiPart/LayerEditWidget.h"
#include "Project/TopologyEditModel.h"
#include "GuiPart/NetParamWidget.h"
namespace Ui{class TopologyWidget;}

/**
 * Contains main application graphical user interface classes.
 */
namespace Application{

/**
 * The TopologyWidget class.
 */
class TopologyWidget : public QWidget{
	Q_OBJECT

	public:
        TopologyWidget(QWidget *parent = 0);
		~TopologyWidget();
		void setModel(TopologyEditModel* model);
		bool hasModel();

	private slots:
		void closeBtnPressed();
		void widgetPressed(LayerEditWidget* widget);
		void appendLayer();
		void duplicateLayer(LayerEditWidget* widget);
		void removeLayer(LayerEditWidget* widget);
		void duplicateSelected();
		void removeSelected();
		void countChanged(LayerEditWidget* widget, int count);
		void modelChanged(ChangeType type);

    private:
		void fillWeightTable();
		int selectedLayer();
		void makeView();
		void clearView();

	signals:
        /** Emmited when close button is pressed. */
		void closePressed(BaseModel*);

	private:
        /** Autogenerated stuff, user interface class pointer. */
		Ui::TopologyWidget *ui;
        /** List of LayerEditWidget class pointers. */
		QList<LayerEditWidget*> layerEditList;
        /** List of lines between layer edit widgets. */
		QList<QFrame*> layerLineList;
        /** Contains layer edit widgets and lines between them. */
		QVBoxLayout* layerEditLayout;
        /** Current model pointer. */
		TopologyEditModel* model;
        /** NetParamWidget class pointer. */
		NetParamWidget* npw;
};

}

#endif // TOPOLOGYWIDGET_H
